---
col_target: SalePrice
col_output: SalePrice_predicted
col_idx: Id
cols_features: []
estimator:
    class: fritz_ds.estimator.adapter.LgbmRegressor
    cols_categorical: []
    params:
        bagging_fraction: 0.8
        bagging_freq: 0
        boosting: gbdt
        cat_l2: 10.0
        cat_smooth: 10.0
        device_type: cpu
        early_stopping_rounds: -1
        extra_trees: false
        feature_fraction: 1.0
        lambda_l1: 0.0
        lambda_l2: 0.0
        learning_rate: 0.3
        linear_lambda: 0.0
        max_cat_to_onehot: 4
        max_depth: 30
        min_data_in_leaf: 50
        n_estimators: 150
        num_leaves: 31
        num_threads: -1
        objective: l2
        seed: 42
        tree_learner: serial
        use_missing: true
        verbosity: 0
        zero_as_missing: false
cv:
    param_grid:
        estimator__max_depth: [10, 30]
        estimator__min_data_in_leaf: [100, 300]
        estimator__num_leaves: [31, 100, 200]
        estimator__n_estimators: [100, 200, 300]
    scoring: neg_mean_squared_error
