---
loader: src/fritz_ds_example/titanic/titanic_data_cfg.yaml
model_cfg: titanic_lgbm.yaml
model_cfg_folder: src/fritz_ds_example/titanic/models
output_folder: outputs
cv_model_file_name: best_cv_{model_name}_model.yaml
trained_model_file_name: trained_{model_name}_model.yaml
pred_df_file_name: predictions_{model_name}.csv
